# Generated by Django 2.2.9 on 2020-03-22 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TINY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(),
        ),
    ]
